# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hacker',
            name='github',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hacker',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
