# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180316_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='skip_crawl',
            field=models.BooleanField(default=False, verbose_name=b'skip crawling this blog'),
        ),
    ]
