# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-24 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20180318_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='last_crawled',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last crawled'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='skip_crawl',
            field=models.BooleanField(default=False, verbose_name='skip crawling this blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='stream',
            field=models.CharField(choices=[('BLOGGING', 'blogging'), ('LOGS', 'Daily Logs')], default='BLOGGING', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation timestamp'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(verbose_name='posted at'),
        ),
    ]
