# Generated by Django 3.2.7 on 2021-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191224_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacker',
            name='zulip_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
